# Generated by Django 5.2.8 on 2025-11-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studyplan_studytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.exam')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('exam', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('youtube', 'YouTube Lesson'), ('notes', 'Study Notes'), ('paper', 'Past Paper')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('source', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('solution_url', models.URLField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.subject')),
            ],
            options={
                'ordering': ['kind', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SubjectWeightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percent', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightages', to='core.subject')),
            ],
            options={
                'ordering': ['-year', 'subject__name'],
            },
        ),
    ]
